name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom version number'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: openwrt-nekobox

    - name: Fix workspace permissions
      run: |
        chmod -R 777 $GITHUB_WORKSPACE

    - name: Verify Makefile exists
      run: |
        if [ ! -f openwrt-nekobox/luci-app-nekobox/Makefile ]; then
          echo "Makefile not found!"
          exit 1
        fi

    - name: Inject version
      run: |
        cd openwrt-nekobox
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${{ github.event.inputs.version }}/" luci-app-nekobox/Makefile
        sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=cn/" luci-app-nekobox/Makefile

    - name: Prepare build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3

    - name: Copy luci-app-nekobox to package directory
      run: |
        cd openwrt-nekobox
        mkdir -p package/luci-app-nekobox
        cp -r luci-app-nekobox/* package/luci-app-nekobox/

    - name: Build package
      run: |
        cd openwrt-nekobox
        make package/luci-app-nekobox/compile V=s

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-nekobox
        path: openwrt-nekobox/bin/packages/*/base/luci-app-nekobox*.ipk

  release:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: luci-app-nekobox

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}-cn
        name: luci-app-nekobox ${{ github.event.inputs.version }}-cn
        files: luci-app-nekobox/*.ipk