name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom version number'     
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openwrt/sdk:x86_64-23.05.3
      options: --user root  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: openwrt-nekobox  

    - name: Fix workspace permissions
      run: |
        chmod -R 777 $GITHUB_WORKSPACE

    - name: Inject version
      run: |
        cd openwrt-nekobox
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${{ github.event.inputs.version }}/" nekobox/Makefile
        sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=cn/" nekobox/Makefile

    - name: Prepare SDK
      run: |
        cd openwrt-nekobox
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build package
      run: |
        cd openwrt-nekobox
        cp -r nekobox package/
        make package/luci-app-nekobox/compile V=s

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-nekobox
        path: openwrt-nekobox/bin/packages/*/base/luci-app-nekobox*.ipk

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: luci-app-nekobox

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}-cn
        name: luci-app-nekobox ${{ github.event.inputs.version }}-cn
        files: luci-app-nekobox/*.ipk