on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom version number'
        required: true
        default: '1.8.5'

jobs:
  build_ipk:
    permissions:
      contents: write
    name: Build Nekobox
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        release:
          - 23.05.4
        arch:
          - x86_64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: Thaolga/openwrt-nekobox
          ref: main

      - name: Preparing Nekobox
        run: |
          mkdir -p feeds artifacts
          cp -rf ./luci-app-nekobox ./feeds/

      - name: Building luci-app-nekobox
        uses: openwrt/gh-action-sdk@v1
        with:
          dockerfile: |
            FROM openwrt/sdk:${{ matrix.release }}-${{ matrix.arch }}
            RUN mkdir -p /home/build/openwrt
            WORKDIR /home/build/openwrt

        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-app-nekobox
          NO_SHFMT_CHECK: 1

      - name: Delivering Package
        uses: actions/upload-artifact@v4
        with:
          name: nekobox-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-app*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Prepare release assets
        run: |
          mkdir -p ./release
          find ./artifacts -name 'luci-app-nekobox*.ipk' -exec cp {} ./release/luci-app-nekobox_${{ github.event.inputs.version }}-cn_all.ipk \;

      - name: Create Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}-cn
          release_name: luci-app-nekobox ${{ github.event.inputs.version }}-cn
          draft: false
          prerelease: true

      - name: Upload release asset
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/luci-app-nekobox_${{ github.event.inputs.version }}-cn_all.ipk
          asset_name: luci-app-nekobox_${{ github.event.inputs.version }}-cn_all.ipk
          asset_content_type: application/octet-stream