name: Build and Release luci-app-nekobox

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom version number'
        required: true
        default: '1.8.5'

jobs:
  build_and_release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Ha3apoBa/openwrt-nekobox
          ref: main
          path: openwrt-nekobox

      - name: Cleanup Git Config
        run: |
          git config --global --unset-all http.https://github.com/.extraheader

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses-dev \
            unzip \
            gawk \
            python3 \
            zlib1g-dev \
            file

      - name: Prepare SDK
        working-directory: ./openwrt-nekobox
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build luci-app-nekobox
        working-directory: ./openwrt-nekobox
        run: |
          make defconfig
          make package/luci-app-nekobox/compile -j$(nproc) V=s || true
          find bin -name "luci-app-nekobox*.ipk" -exec echo "Built package: {}" \;

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: NekoBox ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Upload IPK Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt-nekobox/bin/packages/*/base/luci-app-nekobox_${{ github.event.inputs.version }}*.ipk
          asset_name: luci-app-nekobox_${{ github.event.inputs.version }}.ipk
          asset_content_type: application/octet-stream